name: banking_loan_monorepo

packages:
  - app
  - packages/**

scripts:
  bootstrap:
    run: melos exec -- flutter pub get
    description: Run pub get in all packages

  format:
    run: melos exec -- dart format .
    description: Format all code

  analyze:
    run: melos exec -- dart analyze .
    description: Analyze all packages

  test:
    run: melos exec -- flutter test
    description: Run tests in all packages

  clean:
    run: melos clean
    description: Clean workspace

  build:notespro:
    run: |
      melos exec --dir-exists=app -- cd app && pubm -f pro && flutter pub get
      melos exec --dir-exists=app -- cd app && flutter build apk --release --flavor notespro -t lib/notes/main_pro.dart
    description: Build notespro APK (integrates pubm)
